github-action: cleanup on the build workflow and added tvqagame

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -76,6 +76,7 @@ jobs:
             build/legacy/cgame*.so
             build/legacy/ui*.so
             build/legacy/qagame*.so
+            build/legacy/tvqagame*.so
 
       - uses: actions/upload-artifact@v4
         with:
@@ -109,6 +110,33 @@ jobs:
             build/legacy/cgame*.so
             build/legacy/ui*.so
             build/legacy/qagame*.so
+            build/legacy/tvqagame*.so
+
+  lnx-aarch64-mod:
+    runs-on: ubuntu-20.04
+    needs: version
+    container:
+      image: etlegacy/lnx-aarch64-build
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: true
+
+      - name: Build
+        env:
+          CI_ETL_DESCRIBE: ${{needs.version.outputs.describe}}
+          CI_ETL_TAG: ${{needs.version.outputs.tag}}
+        run: |
+          git config --global --add safe.directory $GITHUB_WORKSPACE
+          ./easybuild.sh build -RPIT -mod -ninja
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: lnx-aarch64-mod
+          path: |
+            build/legacy/cgame*.so
+            build/legacy/ui*.so
+            build/legacy/tvqagame*.so
 
   osx-mod:
     runs-on: macos-12
@@ -145,6 +173,7 @@ jobs:
             build/legacy/cgame_mac
             build/legacy/ui_mac
             build/legacy/qagame_mac
+            build/legacy/tvqagame_mac
 
   win-mod:
     runs-on: windows-2019
@@ -169,6 +198,7 @@ jobs:
             build/legacy/cgame*.dll
             build/legacy/ui*.dll
             build/legacy/qagame*.dll
+            build/legacy/tvqagame*.dll
 
   win64-mod:
     runs-on: windows-2019
@@ -192,32 +222,7 @@ jobs:
           path: |
             build/legacy/cgame*.dll
             build/legacy/ui*.dll
-            build/legacy/qagame*.dll
-
-  lnx-aarch64-mod:
-    runs-on: ubuntu-20.04
-    needs: version
-    container:
-      image: etlegacy/lnx-aarch64-build
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: true
-          fetch-depth: 0
-
-      - name: Build
-        run: |
-          git config --global --add safe.directory $GITHUB_WORKSPACE
-          git fetch --tags --force
-          ./easybuild.sh build -RPIT -mod -ninja
-
-      - uses: actions/upload-artifact@v4
-        with:
-          name: lnx-aarch64-mod
-          path: |
-            build/legacy/cgame*.so
-            build/legacy/ui*.so
-            build/legacy/qagame*.so
+            build/legacy/tvqagame*.dll
 
   android-mod:
     runs-on: ubuntu-20.04
@@ -313,7 +318,7 @@ jobs:
       - name: Create mod zip
         shell: bash
         run: |
-          zip -rvj etlegacy-mod-${{needs.version.outputs.describe}}.zip legacy_*.pk3 platforms/qagame*
+          zip -rvj etlegacy-mod-${{needs.version.outputs.describe}}.zip legacy_*.pk3 platforms/qagame* platforms/tvqagame*
 
       - name: Remove old artifacts
         uses: geekyeggo/delete-artifact@v4
@@ -441,6 +446,45 @@ jobs:
             build/etlegacy-*.tar.gz
             build/etlegacy-*.sh
 
+  lnx-aarch64:
+    runs-on: ubuntu-latest
+    needs: [ version, mod-merger ]
+    container:
+      image: etlegacy/lnx-aarch64-build
+    env:
+      CI_ETL_DESCRIBE: ${{needs.version.outputs.describe}}
+      CI_ETL_TAG: ${{needs.version.outputs.tag}}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: true
+
+      - name: Build
+        run: |
+          git fetch --tags --force
+          ./easybuild.sh build -RPIT -ninja
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: All-mods
+          path: build/legacy
+
+      - name: Display structure of downloaded files
+        run: ls -R
+        working-directory: build/legacy
+
+      - name: Generate packages
+        shell: bash
+        working-directory: build
+        run: cpack
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: lnx-aarch64-packages
+          path: |
+            build/etlegacy-*.tar.gz
+            build/etlegacy-*.sh
+
   osx:
     runs-on: macos-12
     needs: [ version, mod-merger ]
@@ -532,7 +576,6 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: true
-          fetch-depth: 0
 
       - name: Build
         shell: cmd
@@ -560,52 +603,14 @@ jobs:
             build/etlegacy-*.exe
             build/etlegacy-*.zip
 
-  lnx-aarch64:
-    runs-on: ubuntu-latest
-    needs: [ version, mod-merger ]
-    container:
-      image: etlegacy/lnx-aarch64-build
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: true
-          fetch-depth: 0
-
-      - name: Build
-        run: |
-          git config --global --add safe.directory $GITHUB_WORKSPACE
-          git fetch --tags --force
-          ./easybuild.sh build -RPIT -ninja
-
-      - uses: actions/download-artifact@v4
-        with:
-          name: All-mods
-          path: build/legacy
-
-      - name: Display structure of downloaded files
-        run: ls -R
-        working-directory: build/legacy
-
-      - name: Generate packages
-        shell: bash
-        working-directory: build
-        run: cpack
-
-      - uses: actions/upload-artifact@v4
-        with:
-          name: lnx-aarch64-packages
-          path: |
-            build/etlegacy-*.tar.gz
-            build/etlegacy-*.sh
-
   android:
     runs-on: ubuntu-20.04
     env:
-          SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGN_APK_ALLIAS }}
-          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGN_APK_PASS }}
-          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGN_APK_PASS }}
-          CI_ETL_DESCRIBE: ${{needs.version.outputs.describe}}
-          CI_ETL_TAG: ${{needs.version.outputs.tag}}
+      SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGN_APK_ALLIAS }}
+      SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGN_APK_PASS }}
+      SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGN_APK_PASS }}
+      CI_ETL_DESCRIBE: ${{needs.version.outputs.describe}}
+      CI_ETL_TAG: ${{needs.version.outputs.tag}}
     needs: [ version, mod-merger ]
     container:
       image: etlegacy/android-build
@@ -646,7 +651,6 @@ jobs:
       - uses: actions/upload-artifact@v4
         with:
           name: android-packages
-#          path: ${{steps.sign_app.outputs.signedReleaseFile}}
           path: app/build/outputs/apk/release/etlegacy*.apk
 
 #   _    _           _                       _                         _      _____   _
@@ -702,21 +706,21 @@ jobs:
 
   docker:
     runs-on: ubuntu-20.04
-    needs: [ upload ] # only upload to docker if the upload to the site was successfully completed
+    needs: [ version, upload ] # only upload to docker if the upload to the site was successfully completed
     # only run on master
     if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
+    env:
+      CI_ETL_DESCRIBE: ${{needs.version.outputs.describe}}
+      CI_ETL_TAG: ${{needs.version.outputs.tag}}
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: false
-          fetch-depth: 0
+
       - uses: actions/download-artifact@v4
         with:
           name: lnx64-packages
           path: build/package
-
-      - name: Fetch tags
-        run: git fetch --tags --force
 
       - name: Setup folder
         working-directory: build/package
@@ -733,12 +737,9 @@ jobs:
       - name: Get the version
         id: vars
         run: |
-          git_tag=$(git describe --abbrev=7 2>/dev/null)
-          tag_missing=$(docker manifest inspect etlegacy/server:$git_tag > /dev/null ; echo $?)
-          echo "Current tag $git_tag is missing from Docker: $tag_missing"
-          echo "tag=$git_tag" >> $GITHUB_OUTPUT
-          echo "short_tag=$(git describe --abbrev=0 2>/dev/null)" >> $GITHUB_OUTPUT
-          echo "tag_missing=$tag_mising" >> $GITHUB_OUTPUT
+          tag_missing=$(docker manifest inspect etlegacy/server:$CI_ETL_DESCRIBE > /dev/null ; echo $?)
+          echo "Current tag ${{needs.version.outputs.describe}} is missing from Docker: $tag_missing"
+          echo "tag_missing=$tag_missing" >> $GITHUB_OUTPUT
 
       # If we are on any build version then we create the latest-patch version
       - name: Build the server container
@@ -757,12 +758,12 @@ jobs:
 
       # If we are on a release tag, then also create the 'latest' tag on docker hub
       - name: Build and push the latest Docker image
-        if: steps.vars.outputs.tag == steps.vars.outputs.short_tag && steps.vars.outputs.tag_missing == '1' && github.event_name != 'schedule'
+        if: needs.version.outputs.describe == needs.version.outputs.tag && steps.vars.outputs.tag_missing == '1' && github.event_name != 'schedule'
         working-directory: build/package
         run: |
-          docker tag etlegacy/server:latest-patch etlegacy/server:${{steps.vars.outputs.tag}}
+          docker tag etlegacy/server:latest-patch etlegacy/server:$CI_ETL_DESCRIBE
           docker tag etlegacy/server:latest-patch etlegacy/server:latest
-          docker push etlegacy/server:${{steps.vars.outputs.tag}}
+          docker push etlegacy/server:$CI_ETL_DESCRIBE
           docker push etlegacy/server:latest
 
   cleanup:
